del props\rocks\maps\T_MT_Rock_08_AO_R_MT.png
del props\monitor\monitor_occluder_BaseColor.png
del common\maps\dummy_normal.png
del props\temple_bridges_000\temple_bridges_000_4.png
del props\tv_medium_size\T_MediumTV_01_ORM.png
del props\rocks\maps\T_Mt_Rock_04_AO_R_MT.png
del common\maps\indus_ground_color.png
del props\rocks\maps\T_Mt_Rock_15_AO_R_MT.png
del props\rocks\maps\T_Mt_Rock_04_N.png
del props\temple_columns_001\temple_columns_001_0_ao.png
del props\rocks\maps\T_Mt_Rock_03_N.png
del common\maps\Ground048_4K-PNG_orm.png
del props\rocks\maps\T_Mt_Rock_03_AO_R_MT.png
del common\maps\Ground048_4K-PNG_Displacement.png
del props\rocks\maps\T_Mt_Rock_14_N.png
del props\rocks\maps\T_MT_Rock_08_N.png
del props\rocks\maps\T_Mt_Rock_10_BC.png
del props\temple_columns_002\temple_columns_002_0_ao.png
del props\rocks\maps\T_Mt_Rock_11_AO_R_MT.png
del props\rocks\maps\T_MT_Rock_08_BC.png
del props\temple_walls_001\temple_walls_001_4_ao.png
del props\rocks\maps\T_Mt_Rock_10_N.png
del props\temple_columns_001\temple_columns_001_1_ao.png
del props\rocks\maps\T_Mt_Rock_11_N.png
del props\fir_trees\T_Wood_log_norm.png
del props\rocks\maps\T_Mt_Rock_11_BC.png
del props\temple_stairs_000\temple_stairs_000_2_ao.png
del props\forest_pack_000\Spruce_maps\Spruce_Needles_ORM.png
del props\rocks\maps\T_Mt_Rock_03_BC.png
del common\maps\Ground048_4K-PNG_Color.png
del props\tv_medium_size\T_MediumTV_01_Normal.png
del props\rocks\maps\T_Mt_Rock_14_AO_R_MT.png
del props\monitor\grey.png
del props\rocks\maps\T_Mt_Rock_04_BC.png
del props\temple_bridges_000\temple_bridges_000_1.png
del props\temple_bridges_000\temple_bridges_000_3.png
del props\tv_medium_size\T_MediumTV_01_BaseColor.png
del props\temple_walls_000\temple_walls_000_1_ao.png
del props\temple_stairs_000\temple_stairs_000_3_ao.png
del props\rocks\maps\T_Mt_Rock_10_AO_R_MT.png
del props\rocks\maps\T_Mt_Rock_15_N.png
del props\rocks\maps\T_Mt_Rock_14_BC.png
del props\rocks\maps\T_Mt_Rock_15_BC.png
del common\maps\Ground048_4K-PNG_NormalDX.png
del props\fir_trees\T_Wood_log_orm.png